#!/usr/bin/env sh

if [ "$SUPERVISOR_PHP_USER" != "root" ] && [ "$SUPERVISOR_PHP_USER" != "sail" ]; then
    echo "You should set SUPERVISOR_PHP_USER to either 'sail' or 'root'."
    exit 1
fi

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

chmod -R 775 $WORKDIR/bootstrap/cache
chmod -R 775 $WORKDIR/storage

if [ "$SUPERVISOR_PHP_USER" = "root" ]; then
    sed -i 's/^user = www-data/user = sail/' /usr/local/etc/php-fpm.d/www.conf
    sed -i 's/^group = www-data/group = sail/' /usr/local/etc/php-fpm.d/www.conf
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

if [ $# -gt 0 ]; then
    if [ "$SUPERVISOR_PHP_USER" = "root" ]; then
        exec "$@"
    else
        exec su-exec $WWWUSER "$@"
    fi
else
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
