allowBuilds:
  '@parcel/watcher': false
  '@prisma/engines': true
  '@tailwindcss/oxide': false
  better-sqlite3: true
  esbuild: false
  maplibre-gl: false
  prisma: true
  unrs-resolver: false
  vue-demi: false
