import type { Model } from '../../app/types'

export const models: Model[] = [
  {
    id: 'tencent/hy4-preview',
    slug: 'hy4-preview',
    name: 'Tencent Hy4 Preview',
    context_tokens: 1048576,
    intelligence: null,
    tok_per_sec: null,
    open_weight: true,
    release_date: '2026-08-27',
    has_text: true,
    has_vision: false,
    has_reasoning: true,
    best_for: 'agentic coding & sustained multi-step tool use',
    aa: null
  },
  {
    id: 'zai-org/glm-5.3-flash',
    slug: 'glm-5-3-flash',
    name: 'GLM-5.3 Flash',
    context_tokens: 1048576,
    intelligence: 57.5,
    tok_per_sec: 42,
    open_weight: true,
    release_date: '2026-08-26',
    has_text: true,
    has_vision: false,
    has_reasoning: true,
    best_for: 'fast, affordable GLM coding with 1M context',
    aa: 57
  },
  {
    id: 'qwen/qwen3.8-flash',
    slug: 'qwen3-8-flash',
    name: 'Qwen 3.8 Flash',
    context_tokens: 1000000,
    intelligence: null,
    tok_per_sec: null,
    open_weight: true,
    release_date: '2026-08-26',
    has_text: true,
    has_vision: true,
    has_reasoning: true,
    best_for: 'fast low-cost agentic coding & reasoning — production commercial build of Flash-Next (AA 56)',
    aa: 56
  },
  {
    id: 'deepseek/deepseek-v4-flash-vision-exp',
    slug: 'deepseek-v4-flash-vision-exp',
    name: 'DeepSeek V4 Flash Vision Exp',
    context_tokens: 1000000,
    intelligence: null,
    tok_per_sec: null,
    open_weight: null,
    release_date: '2026-08-21',
    has_text: true,
    has_vision: true,
    has_reasoning: null,
    best_for: 'fast hybrid-attention reasoning with vision; images billed as input tokens',
    aa: 51
  },
  {
    id: 'zai-org/glm-5.3',
    slug: 'glm-5-3',
    name: 'GLM-5.3',
    context_tokens: 1000000,
    intelligence: 59.5,
    tok_per_sec: 81,
    open_weight: true,
    release_date: '2026-08-14',
    has_text: true,
    has_vision: false,
    has_reasoning: true,
    best_for: 'frontier coding with emergent cyber capabilities',
    aa: 60
  },
  {
    id: 'qwen/qwen3.8-27b',
    slug: 'qwen3-8-27b',
    name: 'Qwen 3.8 27B',
    context_tokens: 262000,
    intelligence: 52,
    tok_per_sec: 51,
    open_weight: true,
    release_date: '2026-08-14',
    has_text: true,
    has_vision: true,
    has_reasoning: true,
    best_for: 'compact vision-language coding & agentic work',
    aa: 52
  },
  {
    id: 'google/gemini-3.7-flash',
    slug: 'gemini-3-7-flash',
    name: 'Gemini 3.7 Flash',
    context_tokens: 1000000,
    intelligence: 56,
    tok_per_sec: 366,
    open_weight: false,
    release_date: '2026-08-13',
    has_text: true,
    has_vision: true,
    has_reasoning: true,
    best_for: 'higher-quality coding & agentic workflows, fewer tokens',
    aa: 56
  },
  {
    id: 'deepseek/deepseek-v4-pro',
    slug: 'deepseek-v4-pro',
    name: 'DeepSeek V4 Pro (latest)',
    context_tokens: 1000000,
    intelligence: 53.2,
    tok_per_sec: 61,
    open_weight: true,
    release_date: '2026-08-12',
    has_text: true,
    has_vision: false,
    has_reasoning: true,
    best_for: 'hybrid-attention long-context reasoning',
    aa: 53
  },
  {
    id: 'xai/grok-4.6',
    slug: 'grok-4-6',
    name: 'Grok 4.6',
    context_tokens: 500000,
    intelligence: 60.9,
    tok_per_sec: 61,
    open_weight: false,
    release_date: '2026-08-12',
    has_text: true,
    has_vision: false,
    has_reasoning: true,
    best_for: 'frontier performance on coding, knowledge work, and STEM',
    aa: 61
  },
  {
    id: 'meta/muse-spark-1.2',
    slug: 'muse-spark-1-2',
    name: 'Muse Spark 1.2',
    context_tokens: 1000000,
    intelligence: 56.8,
    tok_per_sec: null,
    open_weight: true,
    release_date: '2026-08-05',
    has_text: true,
    has_vision: true,
    has_reasoning: true,
    best_for: 'coding-optimized for agentic workflows and large codebases',
    aa: 57
  },
  {
    id: 'meta/muse-spark-1.2-contributor',
    slug: 'muse-spark-1-2-contributor',
    name: 'Muse Spark 1.2 Contributor',
    context_tokens: 1000000,
    intelligence: 56.8,
    tok_per_sec: null,
    open_weight: true,
    release_date: '2026-08-05',
    has_text: true,
    has_vision: true,
    has_reasoning: true,
    best_for: 'Muse Spark 1.2 at ~95% off',
    aa: 57
  },
  {
    id: 'qwen/qwen3.8-max',
    slug: 'qwen3-8-max',
    name: 'Qwen 3.8 Max',
    context_tokens: 1000000,
    intelligence: 58.1,
    tok_per_sec: 24,
    open_weight: true,
    release_date: '2026-08-03',
    has_text: true,
    has_vision: true,
    has_reasoning: true,
    best_for: 'autonomous long-horizon coding & professional work',
    aa: 58
  },

  {
    id: 'qwen/qwen3.8-max-0902',
    slug: 'qwen3-8-max-0902',
    name: 'Qwen 3.8 Max 0902',
    context_tokens: 1000000,
    intelligence: null,
    tok_per_sec: null,
    open_weight: true,
    release_date: '2026-09-02',
    has_text: true,
    has_vision: true,
    has_reasoning: true,
    best_for: 'upgraded Qwen 3.8 Max: stronger coding & agentic tool use',
    aa: null
  },
  {
    id: 'deepseek/deepseek-v4-flash',
    slug: 'deepseek-v4-flash',
    name: 'DeepSeek V4 Flash (latest)',
    context_tokens: 1000000,
    intelligence: 52,
    tok_per_sec: 129,
    open_weight: true,
    release_date: '2026-07-31',
    has_text: true,
    has_vision: false,
    has_reasoning: true,
    best_for: 'fast hybrid-attention reasoning',
    aa: 52
  },
  {
    id: 'deepseek/deepseek-v4-flash-fast',
    slug: 'deepseek-v4-flash-fast',
    name: 'DeepSeek V4 Flash Fast',
    context_tokens: 1000000,
    intelligence: null,
    tok_per_sec: null,
    open_weight: true,
    release_date: '2026-08-22',
    has_text: true,
    has_vision: false,
    has_reasoning: true,
    best_for: 'low-latency V4 Flash deployment',
    aa: null
  },
  {
    id: 'thinkingmachines/inkling-small',
    slug: 'inkling-small',
    name: 'Inkling Small',
    context_tokens: 1000000,
    intelligence: 41.2,
    tok_per_sec: 116,
    open_weight: true,
    release_date: '2026-07-30',
    has_text: true,
    has_vision: true,
    has_reasoning: true,
    best_for: 'lightweight MoE reasoning at lower cost and latency',
    aa: 41
  },
  {
    id: 'moonshotai/kimi-k3',
    slug: 'kimi-k3',
    name: 'Kimi K3',
    context_tokens: 1000000,
    intelligence: 59.7,
    tok_per_sec: 38,
    open_weight: true,
    release_date: '2026-07-16',
    has_text: true,
    has_vision: true,
    has_reasoning: true,
    best_for: 'long-horizon coding & knowledge work with 1M context',
    aa: 60
  },
  {
    id: 'qwen/qwen3.7-flash',
    slug: 'qwen3-7-flash',
    name: 'Qwen 3.7 Flash',
    context_tokens: 1000000,
    intelligence: null,
    tok_per_sec: null,
    open_weight: true,
    release_date: '2026-07-15',
    has_text: true,
    has_vision: true,
    has_reasoning: true,
    best_for: 'fast low-cost agentic coding & reasoning',
    aa: null
  },
  {
    id: 'thinkingmachines/inkling',
    slug: 'inkling',
    name: 'Inkling',
    context_tokens: 256000,
    intelligence: 42.3,
    tok_per_sec: 51,
    open_weight: true,
    release_date: '2026-07-15',
    has_text: true,
    has_vision: true,
    has_reasoning: true,
    best_for: 'multimodal MoE reasoning',
    aa: 42
  },
  {
    id: 'gpt-5.6-luna',
    slug: 'gpt-5-6-luna',
    name: 'GPT-5.6 Luna',
    context_tokens: 1100000,
    intelligence: 52.3,
    tok_per_sec: 124,
    open_weight: false,
    release_date: '2026-07-09',
    has_text: true,
    has_vision: true,
    has_reasoning: true,
    best_for: 'optimized for cost-sensitive workloads',
    aa: 52
  },
  {
    id: 'gpt-5.6-sol',
    slug: 'gpt-5-6-sol',
    name: 'GPT-5.6 Sol',
    context_tokens: 1100000,
    intelligence: 60.9,
    tok_per_sec: 70,
    open_weight: false,
    release_date: '2026-07-09',
    has_text: true,
    has_vision: true,
    has_reasoning: true,
    best_for: 'frontier model for complex professional work',
    aa: 61
  },
  {
    id: 'xai/grok-4.5',
    slug: 'grok-4-5',
    name: 'Grok 4.5',
    context_tokens: 500000,
    intelligence: 55.8,
    tok_per_sec: 49,
    open_weight: false,
    release_date: '2026-07-08',
    has_text: true,
    has_vision: true,
    has_reasoning: true,
    best_for: 'smartest model for coding, agentic tasks, knowledge work',
    aa: 56
  },
  {
    id: 'tencent/hy3-paid',
    slug: 'tencent-hy3',
    name: 'Tencent Hy3',
    context_tokens: 262000,
    intelligence: 42.2,
    tok_per_sec: 69,
    open_weight: true,
    release_date: '2026-07-06',
    has_text: true,
    has_vision: false,
    has_reasoning: true,
    best_for: 'sparse-MoE reasoning & agentic tool use',
    aa: 42
  },
  {
    id: 'meituan/longcat-2.0',
    slug: 'longcat-2-0',
    name: 'LongCat 2.0',
    context_tokens: 1048576,
    intelligence: null,
    tok_per_sec: null,
    open_weight: true,
    release_date: '2026-06-30',
    has_text: true,
    has_vision: false,
    has_reasoning: true,
    best_for: 'trillion-param MoE coding & agentic work with 1M context',
    aa: 34
  },
  {
    id: 'zai-org/glm-5.2-fast',
    slug: 'glm-5-2-fast',
    name: 'GLM-5.2 Fast',
    context_tokens: 1000000,
    intelligence: null,
    tok_per_sec: null,
    open_weight: true,
    release_date: '2026-06-23',
    has_text: true,
    has_vision: false,
    has_reasoning: false,
    best_for: 'high-throughput GLM-5.2 with 1M context',
    aa: null
  },
  {
    id: 'zai-org/glm-5.2',
    slug: 'glm-5-2',
    name: 'GLM-5.2',
    context_tokens: 1000000,
    intelligence: 52.6,
    tok_per_sec: 69,
    open_weight: true,
    release_date: '2026-06-13',
    has_text: true,
    has_vision: false,
    has_reasoning: true,
    best_for: 'powerful coding with 1M context and long-horizon tasks',
    aa: 53
  },
  {
    id: 'moonshotai/kimi-k2.7-code-highspeed',
    slug: 'kimi-k2-7-code-highspeed',
    name: 'Kimi K2.7 Code HighSpeed',
    context_tokens: 262000,
    intelligence: null,
    tok_per_sec: null,
    open_weight: true,
    release_date: '2026-06-12',
    has_text: true,
    has_vision: true,
    has_reasoning: true,
    best_for: 'high-speed long-horizon coding with vision',
    aa: null
  },
  {
    id: 'moonshotai/kimi-k2.7-code',
    slug: 'kimi-k2-7-code',
    name: 'Kimi K2.7 Code',
    context_tokens: 256000,
    intelligence: 43,
    tok_per_sec: 40,
    open_weight: true,
    release_date: '2026-06-12',
    has_text: true,
    has_vision: true,
    has_reasoning: true,
    best_for: 'improved long-horizon coding with vision',
    aa: 43
  },
  {
    id: 'nvidia/nemotron-3-ultra-550b-a55b',
    slug: 'nemotron-3-ultra-550b-a55b',
    name: 'Nemotron 3 Ultra',
    context_tokens: 1000000,
    intelligence: 38.3,
    tok_per_sec: 174,
    open_weight: true,
    release_date: '2026-06-04',
    has_text: true,
    has_vision: false,
    has_reasoning: true,
    best_for: 'open reasoning model for long-horizon autonomous agents',
    aa: 38
  },
  {
    id: 'qwen/qwen3.7-plus',
    slug: 'qwen3-7-plus',
    name: 'Qwen 3.7 Plus',
    context_tokens: 1000000,
    intelligence: 39.4,
    tok_per_sec: 56,
    open_weight: true,
    release_date: '2026-06-02',
    has_text: true,
    has_vision: true,
    has_reasoning: true,
    best_for: 'agentic coding & reasoning at lower cost',
    aa: 39
  },
  {
    id: 'minimaxai/minimax-m3',
    slug: 'minimax-m3',
    name: 'MiniMax M3',
    context_tokens: 1000000,
    intelligence: 45.4,
    tok_per_sec: 111,
    open_weight: true,
    release_date: '2026-06-01',
    has_text: true,
    has_vision: true,
    has_reasoning: true,
    best_for: 'frontier coding, agents & native multimodality',
    aa: 45
  },
  {
    id: 'stepfun/step-3.7-flash',
    slug: 'step-3-7-flash',
    name: 'Step 3.7 Flash',
    context_tokens: 256000,
    intelligence: 30.9,
    tok_per_sec: 94,
    open_weight: true,
    release_date: '2026-05-29',
    has_text: true,
    has_vision: true,
    has_reasoning: true,
    best_for: 'multimodal sparse-MoE reasoning',
    aa: 31
  },
  {
    id: 'qwen/qwen3.7-max',
    slug: 'qwen3-7-max',
    name: 'Qwen 3.7 Max',
    context_tokens: 1000000,
    intelligence: 46.7,
    tok_per_sec: null,
    open_weight: true,
    release_date: '2026-05-21',
    has_text: true,
    has_vision: false,
    has_reasoning: true,
    best_for: 'frontier coding & long-horizon agent execution',
    aa: 47
  },
  {
    id: 'xiaomi/mimo-v2.5',
    slug: 'mimo-v2-5',
    name: 'MiMo V2.5',
    context_tokens: 1000000,
    intelligence: 38,
    tok_per_sec: 64,
    open_weight: true,
    release_date: '2026-04-22',
    has_text: true,
    has_vision: true,
    has_reasoning: false,
    best_for: 'efficient long-context agentic coding',
    aa: 38
  },
  {
    id: 'xiaomi/mimo-v2.5-pro',
    slug: 'mimo-v2-5-pro',
    name: 'MiMo V2.5 Pro',
    context_tokens: 1000000,
    intelligence: 42.9,
    tok_per_sec: 43,
    open_weight: true,
    release_date: '2026-04-22',
    has_text: true,
    has_vision: false,
    has_reasoning: false,
    best_for: 'high-capability long-context agentic coding',
    aa: 43
  },
  {
    id: 'moonshotai/kimi-k2.6',
    slug: 'kimi-k2-6',
    name: 'Kimi K2.6',
    context_tokens: 256000,
    intelligence: 45.1,
    tok_per_sec: null,
    open_weight: true,
    release_date: '2026-04-21',
    has_text: true,
    has_vision: true,
    has_reasoning: false,
    best_for: 'long-horizon coding with vision',
    aa: 45
  },
  {
    id: 'qwen/qwen3.6-max-preview',
    slug: 'qwen3-6-max-preview',
    name: 'Qwen 3.6 Max Preview',
    context_tokens: 200000,
    intelligence: 41.1,
    tok_per_sec: null,
    open_weight: true,
    release_date: '2026-04-20',
    has_text: true,
    has_vision: false,
    has_reasoning: true,
    best_for: 'vibe coding & efficient agent execution',
    aa: 41
  },
  {
    id: 'zai-org/glm-5.1',
    slug: 'glm-5-1',
    name: 'GLM-5.1',
    context_tokens: 200000,
    intelligence: 41,
    tok_per_sec: 28,
    open_weight: true,
    release_date: '2026-04-07',
    has_text: true,
    has_vision: false,
    has_reasoning: false,
    best_for: 'long-horizon autonomous coding agent',
    aa: 41
  },
  {
    id: 'qwen/qwen3.6-plus',
    slug: 'qwen3-6-plus',
    name: 'Qwen 3.6 Plus',
    context_tokens: 200000,
    intelligence: 40.5,
    tok_per_sec: null,
    open_weight: true,
    release_date: '2026-04-02',
    has_text: true,
    has_vision: true,
    has_reasoning: true,
    best_for: 'agentic coding & reasoning',
    aa: 40
  },
  {
    id: 'minimaxai/minimax-m2.7',
    slug: 'minimax-m2-7',
    name: 'MiniMax M2.7',
    context_tokens: 200000,
    intelligence: 38.9,
    tok_per_sec: null,
    open_weight: true,
    release_date: '2026-03-18',
    has_text: true,
    has_vision: false,
    has_reasoning: false,
    best_for: 'end-to-end software engineering agent',
    aa: 39
  },
  {
    id: 'minimaxai/minimax-m2.5',
    slug: 'minimax-m2-5',
    name: 'MiniMax M2.5',
    context_tokens: 200000,
    intelligence: 34.5,
    tok_per_sec: null,
    open_weight: true,
    release_date: '2026-02-12',
    has_text: true,
    has_vision: false,
    has_reasoning: false,
    best_for: 'cross-platform full-stack agentic dev',
    aa: 34
  },
  {
    id: 'zai-org/glm-5',
    slug: 'glm-5',
    name: 'GLM-5',
    context_tokens: 200000,
    intelligence: 40.6,
    tok_per_sec: null,
    open_weight: true,
    release_date: '2026-02-12',
    has_text: true,
    has_vision: false,
    has_reasoning: false,
    best_for: 'multi-mode thinking & long-range planning',
    aa: 41
  },
  {
    id: 'stepfun/step-3.5-flash',
    slug: 'step-3-5-flash',
    name: 'Step 3.5 Flash',
    context_tokens: 1000000,
    intelligence: 26.5,
    tok_per_sec: null,
    open_weight: true,
    release_date: '2026-01-29',
    has_text: true,
    has_vision: false,
    has_reasoning: true,
    best_for: 'fast sparse-MoE agentic reasoning',
    aa: 27
  },
  {
    id: 'moonshotai/kimi-k2.5',
    slug: 'kimi-k2-5',
    name: 'Kimi K2.5',
    context_tokens: 256000,
    intelligence: 36,
    tok_per_sec: null,
    open_weight: true,
    release_date: '2026-01-27',
    has_text: true,
    has_vision: true,
    has_reasoning: false,
    best_for: 'multimodal frontend coding',
    aa: 36
  }
]
