import type { PricingEntry } from '../../app/types'

export const pricing: PricingEntry[] = [
  {
    provider_id: 'command-code',
    model_id: 'tencent/hy4-preview',
    tier: 'standard',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 0.834,
    output: 2.501,
    cache_read: 0.042,
    cache_write: null
  },
  {
    provider_id: 'opencode',
    model_id: 'tencent/hy4-preview',
    tier: 'standard',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 0.834,
    output: 2.501,
    cache_read: 0.042,
    cache_write: null
  },
  {
    provider_id: 'command-code',
    model_id: 'zai-org/glm-5.3-flash',
    tier: 'standard',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 0.15,
    output: 0.5,
    cache_read: 0.03,
    cache_write: null
  },
  {
    provider_id: 'opencode',
    model_id: 'zai-org/glm-5.3-flash',
    tier: 'standard',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 0.15,
    output: 0.5,
    cache_read: 0.03,
    cache_write: null
  },
  {
    provider_id: 'command-code',
    model_id: 'qwen/qwen3.8-flash',
    tier: 'standard',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 0.16,
    output: 0.47,
    cache_read: 0.016,
    cache_write: null
  },
  {
    provider_id: 'opencode',
    model_id: 'qwen/qwen3.8-flash',
    tier: 'standard',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 0.15,
    output: 0.47,
    cache_read: 0.016,
    cache_write: 0.20
  },
  {
    provider_id: 'command-code',
    model_id: 'deepseek/deepseek-v4-flash-vision-exp',
    tier: 'off_peak',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 0.22,
    output: 0.66,
    cache_read: 0.007,
    cache_write: null
  },
  {
    provider_id: 'command-code',
    model_id: 'deepseek/deepseek-v4-flash-vision-exp',
    tier: 'peak',
    max_context_tokens: null,
    peak_utc_hours: '01-04,06-10',
    input: 0.44,
    output: 1.32,
    cache_read: 0.014,
    cache_write: null
  },
  {
    provider_id: 'opencode',
    model_id: 'deepseek/deepseek-v4-flash-vision-exp',
    tier: 'off_peak',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 0.22,
    output: 0.66,
    cache_read: 0.007,
    cache_write: null
  },
  {
    provider_id: 'opencode',
    model_id: 'deepseek/deepseek-v4-flash-vision-exp',
    tier: 'peak',
    max_context_tokens: null,
    peak_utc_hours: '01-04,06-10',
    input: 0.44,
    output: 1.32,
    cache_read: 0.014,
    cache_write: null
  },
  {
    provider_id: 'command-code',
    model_id: 'zai-org/glm-5.3',
    tier: 'standard',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 1.4,
    output: 4.4,
    cache_read: 0.26,
    cache_write: null
  },
  {
    provider_id: 'opencode',
    model_id: 'zai-org/glm-5.3',
    tier: 'standard',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 1.4,
    output: 4.4,
    cache_read: 0.26,
    cache_write: null
  },
  {
    provider_id: 'command-code',
    model_id: 'qwen/qwen3.8-27b',
    tier: 'standard',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 0.4,
    output: 3,
    cache_read: 0.04,
    cache_write: null
  },
  {
    provider_id: 'command-code',
    model_id: 'google/gemini-3.7-flash',
    tier: 'standard',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 1.5,
    output: 7.5,
    cache_read: 0.15,
    cache_write: 0.08334
  },
  {
    provider_id: 'command-code',
    model_id: 'deepseek/deepseek-v4-pro',
    tier: 'off_peak',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 0.66,
    output: 1.98,
    cache_read: 0.022,
    cache_write: null
  },
  {
    provider_id: 'command-code',
    model_id: 'deepseek/deepseek-v4-pro',
    tier: 'peak',
    max_context_tokens: null,
    peak_utc_hours: '01-04,06-10',
    input: 1.32,
    output: 3.96,
    cache_read: 0.044,
    cache_write: null
  },
  {
    provider_id: 'opencode',
    model_id: 'deepseek/deepseek-v4-pro',
    tier: 'off_peak',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 0.66,
    output: 1.98,
    cache_read: 0.022,
    cache_write: null
  },
  {
    provider_id: 'opencode',
    model_id: 'deepseek/deepseek-v4-pro',
    tier: 'peak',
    max_context_tokens: null,
    peak_utc_hours: '01-04,06-10',
    input: 1.32,
    output: 3.96,
    cache_read: 0.044,
    cache_write: null
  },
  {
    provider_id: 'command-code',
    model_id: 'xai/grok-4.6',
    tier: 'standard',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 2,
    output: 6,
    cache_read: 0.5,
    cache_write: null
  },
  {
    provider_id: 'opencode',
    model_id: 'xai/grok-4.6',
    tier: 'standard',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 2,
    output: 6,
    cache_read: 0.5,
    cache_write: null
  },
  {
    provider_id: 'command-code',
    model_id: 'meta/muse-spark-1.2',
    tier: 'standard',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 1.25,
    output: 4.25,
    cache_read: 0.15,
    cache_write: null
  },
  {
    provider_id: 'command-code',
    model_id: 'meta/muse-spark-1.2-contributor',
    tier: 'standard',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 0.1,
    output: 0.2,
    cache_read: 0.002,
    cache_write: null
  },
  {
    provider_id: 'opencode',
    model_id: 'meta/muse-spark-1.2-contributor',
    tier: 'standard',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 0.1,
    output: 0.2,
    cache_read: 0.002,
    cache_write: null
  },
  {
    provider_id: 'command-code',
    model_id: 'qwen/qwen3.8-max',
    tier: 'standard',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 2,
    output: 6,
    cache_read: 0.25,
    cache_write: 2.5
  },

  {
    provider_id: 'command-code',
    model_id: 'qwen/qwen3.8-max-0902',
    tier: 'standard',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 2,
    output: 6,
    cache_read: 0.25,
    cache_write: null
  },
  {
    provider_id: 'opencode',
    model_id: 'qwen/qwen3.8-max',
    tier: 'standard',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 2,
    output: 6,
    cache_read: 0.25,
    cache_write: 2.5
  },
  {
    provider_id: 'command-code',
    model_id: 'deepseek/deepseek-v4-flash',
    tier: 'off_peak',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 0.22,
    output: 0.66,
    cache_read: 0.007,
    cache_write: null
  },
  {
    provider_id: 'command-code',
    model_id: 'deepseek/deepseek-v4-flash-fast',
    tier: 'off_peak',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 0.28,
    output: 0.56,
    cache_read: 0.07,
    cache_write: null
  },
  {
    provider_id: 'command-code',
    model_id: 'deepseek/deepseek-v4-flash',
    tier: 'peak',
    max_context_tokens: null,
    peak_utc_hours: '01-04,06-10',
    input: 0.44,
    output: 1.32,
    cache_read: 0.014,
    cache_write: null
  },
  {
    provider_id: 'opencode',
    model_id: 'deepseek/deepseek-v4-flash',
    tier: 'off_peak',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 0.22,
    output: 0.66,
    cache_read: 0.007,
    cache_write: null
  },
  {
    provider_id: 'opencode',
    model_id: 'deepseek/deepseek-v4-flash',
    tier: 'peak',
    max_context_tokens: null,
    peak_utc_hours: '01-04,06-10',
    input: 0.44,
    output: 1.32,
    cache_read: 0.014,
    cache_write: null
  },
  {
    provider_id: 'command-code',
    model_id: 'thinkingmachines/inkling-small',
    tier: 'standard',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 0.5,
    output: 1.2,
    cache_read: 0.1,
    cache_write: null
  },
  {
    provider_id: 'command-code',
    model_id: 'moonshotai/kimi-k3',
    tier: 'standard',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 3,
    output: 15,
    cache_read: 0.3,
    cache_write: null
  },
  {
    provider_id: 'opencode',
    model_id: 'moonshotai/kimi-k3',
    tier: 'standard',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 3,
    output: 15,
    cache_read: 0.3,
    cache_write: null
  },
  {
    provider_id: 'command-code',
    model_id: 'qwen/qwen3.7-flash',
    tier: 'standard',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 0.03,
    output: 0.13,
    cache_read: 0.006,
    cache_write: 0.038
  },
  {
    provider_id: 'command-code',
    model_id: 'thinkingmachines/inkling',
    tier: 'standard',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 1,
    output: 4.05,
    cache_read: 0.17,
    cache_write: null
  },
  {
    provider_id: 'command-code',
    model_id: 'gpt-5.6-luna',
    tier: 'standard',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 0.2,
    output: 1.2,
    cache_read: 0.02,
    cache_write: 0.25
  },
  {
    provider_id: 'opencode',
    model_id: 'gpt-5.6-luna',
    tier: 'ctx_low',
    max_context_tokens: 272000,
    peak_utc_hours: null,
    input: 0.2,
    output: 1.2,
    cache_read: 0.02,
    cache_write: 0.25
  },
  {
    provider_id: 'opencode',
    model_id: 'gpt-5.6-luna',
    tier: 'ctx_high',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 0.4,
    output: 1.8,
    cache_read: 0.04,
    cache_write: 0.5
  },
  {
    provider_id: 'command-code',
    model_id: 'gpt-5.6-sol',
    tier: 'standard',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 5,
    output: 30,
    cache_read: 0.5,
    cache_write: 6.25
  },
  {
    provider_id: 'command-code',
    model_id: 'xai/grok-4.5',
    tier: 'standard',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 2,
    output: 6,
    cache_read: 0.5,
    cache_write: null
  },
  {
    provider_id: 'opencode',
    model_id: 'xai/grok-4.5',
    tier: 'standard',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 2,
    output: 6,
    cache_read: 0.3,
    cache_write: null
  },
  {
    provider_id: 'command-code',
    model_id: 'tencent/hy3-paid',
    tier: 'standard',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 0.14,
    output: 0.58,
    cache_read: 0.035,
    cache_write: null
  },
  {
    provider_id: 'opencode',
    model_id: 'tencent/hy3-paid',
    tier: 'standard',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 0.14,
    output: 0.58,
    cache_read: 0.035,
    cache_write: null
  },
  {
    provider_id: 'opencode',
    model_id: 'meituan/longcat-2.0',
    tier: 'standard',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 0.3,
    output: 1.2,
    cache_read: 0.006,
    cache_write: null
  },
  {
    provider_id: 'command-code',
    model_id: 'zai-org/glm-5.2-fast',
    tier: 'standard',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 3,
    output: 10.25,
    cache_read: 0.5,
    cache_write: null
  },
  {
    provider_id: 'command-code',
    model_id: 'zai-org/glm-5.2',
    tier: 'standard',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 1.4,
    output: 4.4,
    cache_read: 0.26,
    cache_write: null
  },
  {
    provider_id: 'opencode',
    model_id: 'zai-org/glm-5.2',
    tier: 'standard',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 1.4,
    output: 4.4,
    cache_read: 0.26,
    cache_write: null
  },
  {
    provider_id: 'command-code',
    model_id: 'moonshotai/kimi-k2.7-code-highspeed',
    tier: 'standard',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 1.9,
    output: 8,
    cache_read: 0.38,
    cache_write: null
  },
  {
    provider_id: 'command-code',
    model_id: 'moonshotai/kimi-k2.7-code',
    tier: 'standard',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 0.95,
    output: 4,
    cache_read: 0.19,
    cache_write: null
  },
  {
    provider_id: 'opencode',
    model_id: 'moonshotai/kimi-k2.7-code',
    tier: 'standard',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 0.95,
    output: 4,
    cache_read: 0.19,
    cache_write: null
  },
  {
    provider_id: 'command-code',
    model_id: 'nvidia/nemotron-3-ultra-550b-a55b',
    tier: 'standard',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 0.6,
    output: 2.4,
    cache_read: 0.12,
    cache_write: null
  },
  {
    provider_id: 'command-code',
    model_id: 'qwen/qwen3.7-plus',
    tier: 'standard',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 0.4,
    output: 1.6,
    cache_read: 0.08,
    cache_write: 0.5
  },
  {
    provider_id: 'opencode',
    model_id: 'qwen/qwen3.7-plus',
    tier: 'ctx_low',
    max_context_tokens: 256000,
    peak_utc_hours: null,
    input: 0.4,
    output: 1.6,
    cache_read: 0.04,
    cache_write: 0.5
  },
  {
    provider_id: 'opencode',
    model_id: 'qwen/qwen3.7-plus',
    tier: 'ctx_high',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 1.2,
    output: 4.8,
    cache_read: 0.12,
    cache_write: 1.5
  },
  {
    provider_id: 'command-code',
    model_id: 'minimaxai/minimax-m3',
    tier: 'standard',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 0.6,
    output: 2.4,
    cache_read: 0.12,
    cache_write: null
  },
  {
    provider_id: 'opencode',
    model_id: 'minimaxai/minimax-m3',
    tier: 'standard',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 0.3,
    output: 1.2,
    cache_read: 0.06,
    cache_write: null
  },
  {
    provider_id: 'command-code',
    model_id: 'stepfun/step-3.7-flash',
    tier: 'standard',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 0.2,
    output: 1.15,
    cache_read: 0.04,
    cache_write: null
  },
  {
    provider_id: 'command-code',
    model_id: 'qwen/qwen3.7-max',
    tier: 'standard',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 2.5,
    output: 7.5,
    cache_read: 0.5,
    cache_write: 3.13
  },
  {
    provider_id: 'opencode',
    model_id: 'qwen/qwen3.7-max',
    tier: 'standard',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 2.5,
    output: 7.5,
    cache_read: 0.5,
    cache_write: 3.125
  },
  {
    provider_id: 'command-code',
    model_id: 'xiaomi/mimo-v2.5',
    tier: 'standard',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 0.8,
    output: 4,
    cache_read: 0.16,
    cache_write: null
  },
  {
    provider_id: 'opencode',
    model_id: 'xiaomi/mimo-v2.5',
    tier: 'standard',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 0.14,
    output: 0.28,
    cache_read: 0.0028,
    cache_write: null
  },
  {
    provider_id: 'command-code',
    model_id: 'xiaomi/mimo-v2.5-pro',
    tier: 'standard',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 2,
    output: 6,
    cache_read: 0.4,
    cache_write: null
  },
  {
    provider_id: 'opencode',
    model_id: 'xiaomi/mimo-v2.5-pro',
    tier: 'standard',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 0.435,
    output: 0.87,
    cache_read: 0.003625,
    cache_write: null
  },
  {
    provider_id: 'command-code',
    model_id: 'moonshotai/kimi-k2.6',
    tier: 'standard',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 0.95,
    output: 4,
    cache_read: 0.16,
    cache_write: null
  },
  {
    provider_id: 'opencode',
    model_id: 'moonshotai/kimi-k2.6',
    tier: 'standard',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 0.95,
    output: 4,
    cache_read: 0.16,
    cache_write: null
  },
  {
    provider_id: 'command-code',
    model_id: 'qwen/qwen3.6-max-preview',
    tier: 'standard',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 1.3,
    output: 7.8,
    cache_read: 0.26,
    cache_write: 1.63
  },
  {
    provider_id: 'command-code',
    model_id: 'zai-org/glm-5.1',
    tier: 'standard',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 1.4,
    output: 4.4,
    cache_read: 0.26,
    cache_write: null
  },
  {
    provider_id: 'opencode',
    model_id: 'zai-org/glm-5.1',
    tier: 'standard',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 1.4,
    output: 4.4,
    cache_read: 0.26,
    cache_write: null
  },
  {
    provider_id: 'command-code',
    model_id: 'qwen/qwen3.6-plus',
    tier: 'standard',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 0.5,
    output: 3,
    cache_read: 0.1,
    cache_write: null
  },
  {
    provider_id: 'opencode',
    model_id: 'qwen/qwen3.6-plus',
    tier: 'ctx_low',
    max_context_tokens: 256000,
    peak_utc_hours: null,
    input: 0.5,
    output: 3,
    cache_read: 0.05,
    cache_write: 0.625
  },
  {
    provider_id: 'opencode',
    model_id: 'qwen/qwen3.6-plus',
    tier: 'ctx_high',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 2,
    output: 6,
    cache_read: 0.2,
    cache_write: 2.5
  },
  {
    provider_id: 'command-code',
    model_id: 'minimaxai/minimax-m2.7',
    tier: 'standard',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 0.3,
    output: 1.2,
    cache_read: 0.06,
    cache_write: null
  },
  {
    provider_id: 'opencode',
    model_id: 'minimaxai/minimax-m2.7',
    tier: 'standard',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 0.3,
    output: 1.2,
    cache_read: 0.06,
    cache_write: 0.375
  },
  {
    provider_id: 'command-code',
    model_id: 'minimaxai/minimax-m2.5',
    tier: 'standard',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 0.3,
    output: 1.2,
    cache_read: 0.03,
    cache_write: null
  },
  {
    provider_id: 'opencode',
    model_id: 'minimaxai/minimax-m2.5',
    tier: 'standard',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 0.3,
    output: 1.2,
    cache_read: 0.06,
    cache_write: 0.375
  },
  {
    provider_id: 'command-code',
    model_id: 'zai-org/glm-5',
    tier: 'standard',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 1,
    output: 3.2,
    cache_read: 0.2,
    cache_write: null
  },
  {
    provider_id: 'command-code',
    model_id: 'stepfun/step-3.5-flash',
    tier: 'standard',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 0.1,
    output: 0.3,
    cache_read: 0.02,
    cache_write: null
  },
  {
    provider_id: 'command-code',
    model_id: 'moonshotai/kimi-k2.5',
    tier: 'standard',
    max_context_tokens: null,
    peak_utc_hours: null,
    input: 0.6,
    output: 3,
    cache_read: 0.1,
    cache_write: null
  }
]
